/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AcountModel
 */
export interface AcountModel {
    /**
     * 
     * @type {number}
     * @memberof AcountModel
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AcountModel
     */
    'phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AcountModel
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AcountModel
     */
    'password'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AcountModel
     */
    'salt'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AcountModel
     */
    'active'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof AcountModel
     */
    'fullName'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AcountModel
     */
    'roleId'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AcountModel
     */
    'lastLogin'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AcountModel
     */
    'createDate'?: string | null;
}

