/* tslint:disable */
/* eslint-disable */
/**
 * Auth
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignUpModel
 */
export interface SignUpModel {
    /**
     * 
     * @type {string}
     * @memberof SignUpModel
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof SignUpModel
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof SignUpModel
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof SignUpModel
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof SignUpModel
     */
    'confirmPassword': string;
}

